シリアル出力にステータスをつけた
realglobe-Inc/usb_temperature_humidity pull request #7
Opened 2020-09-17 12:59 UTC by urib0

#6

2020-09-24 17:49 UTC, miminashi requested changes

2020-09-24 17:49 UTC, miminashi commented on usb_temperature_humidity.ino
> +  Serial.println(STATUS_OK);
改行コードはLFに統一しようと思うので、`println`ではなくて、

```c
Serial.print(STATUS_OK);
Serial.print("\n");
```

みたいな感じにしてほしいです。

2020-09-25 05:57 UTC, urib0 commented on usb_temperature_humidity.ino
> +  Serial.println(STATUS_OK);
対応しました！

2020-10-02 09:07 UTC, kirisaki approved these changes

2020-10-02 09:18 UTC, kirisaki approved these changes

2020-10-02 09:25 UTC, miminashi approved these changes
LGTM

2020-10-02 09:25 UTC, merged